FROM sonarqube:10.6-community

USER root

RUN apt update
RUN apt install -y curl

USER sonarqube

HEALTHCHECK --interval=10s --timeout=20s --retries=15 \
  CMD curl -s "http://localhost:9000/api/system/status" | grep '"status":"UP"' || exit 1