FROM sonarqube:8.9-community

RUN apk update
RUN apk add curl

HEALTHCHECK --interval=10s --timeout=20s --retries=15 \
  CMD curl -s "http://localhost:9000/api/system/status" | grep '"status":"UP"' || exit 1